// Generate .github/copilot-instructions.md from a knowledge.yaml manifest.
// This is the Phase 3a "kcp-instructions-gen" feature.

import { resolve } from "node:path";
import { parseFile } from "./parser.js";
import { scopePriority } from "./mapper.js";
import type { KnowledgeManifest, KnowledgeUnit } from "./model.js";

export interface GenerateInstructionsOptions {
  /** Only include units whose audience array contains this value. */
  audience?: string;
}

/**
 * Generate copilot-instructions.md content from a knowledge.yaml manifest.
 *
 * Units are sorted by scope priority (global first) then alphabetically by id.
 * If an audience filter is provided, only units matching that audience are included.
 */
export function generateInstructions(
  manifestPath: string,
  options: GenerateInstructionsOptions = {}
): string {
  const resolvedPath = resolve(manifestPath);
  const manifest = parseFile(resolvedPath);
  return formatInstructions(manifest, options);
}

/**
 * Format a parsed manifest into copilot-instructions.md content.
 * Exported for testing without file I/O.
 */
export function formatInstructions(
  manifest: KnowledgeManifest,
  options: GenerateInstructionsOptions = {}
): string {
  const { audience } = options;

  // Filter units by audience if specified
  let units: KnowledgeUnit[] = manifest.units;
  if (audience) {
    units = units.filter((u) => u.audience.includes(audience));
  }

  // Sort by scope priority descending, then alphabetical by id
  units = [...units].sort((a, b) => {
    const priDiff = scopePriority(b.scope) - scopePriority(a.scope);
    if (priDiff !== 0) return priDiff;
    return a.id.localeCompare(b.id);
  });

  const lines: string[] = [];

  // Header comment
  lines.push(
    `<!-- Generated by kcp-mcp --generate-instructions from knowledge.yaml -->`
  );
  lines.push(
    `<!-- Project: ${manifest.project} | Version: ${manifest.version}` +
      (manifest.kcp_version ? ` | KCP: ${manifest.kcp_version}` : "") +
      (manifest.updated ? ` | Updated: ${manifest.updated}` : "") +
      ` -->`
  );
  lines.push("");

  // Title
  lines.push(`# AI Assistant Instructions: ${manifest.project}`);
  lines.push("");
  lines.push(
    "This repository uses the Knowledge Context Protocol (KCP) to structure knowledge for AI assistants."
  );
  lines.push("");

  // Units section
  lines.push("## Available Knowledge Units");
  lines.push("");

  for (const unit of units) {
    lines.push(`### ${unit.id}`);
    lines.push(`**Intent:** ${unit.intent}`);
    lines.push(
      `**Path:** \`${unit.path}\` | **Scope:** ${unit.scope} | **Audience:** ${unit.audience.join(", ")}`
    );
    if (unit.triggers.length > 0) {
      lines.push(`*Triggers: ${unit.triggers.join(", ")}*`);
    }
    if (unit.depends_on.length > 0) {
      lines.push(`*Requires: ${unit.depends_on.join(", ")}*`);
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Relationships section
  if (manifest.relationships.length > 0) {
    lines.push("## Relationships");
    lines.push("");
    for (const rel of manifest.relationships) {
      lines.push(`- **${rel.from_id}** ${rel.type} **${rel.to_id}**`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
