// Generate .github/copilot-instructions.md from a knowledge.yaml manifest.
// This is the Phase 3a "kcp-instructions-gen" feature.

import { resolve } from "node:path";
import { parseFile } from "./parser.js";
import { scopePriority } from "./mapper.js";
import type { KnowledgeManifest, KnowledgeUnit } from "./model.js";

export interface GenerateInstructionsOptions {
  /** Only include units whose audience array contains this value. */
  audience?: string;
  /** Output format: full (verbose headings), compact (table), agent (agent-oriented). Default: full. */
  format?: "full" | "compact" | "agent";
}

export interface GenerateAgentFileOptions {
  /** Only include units whose audience array contains this value. */
  audience?: string;
  /** Max chars for agent file. Drops module-scope, then project-scope units to fit. */
  maxChars?: number;
}

/**
 * Generate copilot-instructions.md content from a knowledge.yaml manifest.
 *
 * Units are sorted by scope priority (global first) then alphabetically by id.
 * If an audience filter is provided, only units matching that audience are included.
 */
export function generateInstructions(
  manifestPath: string,
  options: GenerateInstructionsOptions = {}
): string {
  const resolvedPath = resolve(manifestPath);
  const manifest = parseFile(resolvedPath);
  return formatInstructions(manifest, options);
}

/**
 * Filter and sort units for instruction generation.
 */
function prepareUnits(
  manifest: KnowledgeManifest,
  audience?: string
): KnowledgeUnit[] {
  let units: KnowledgeUnit[] = manifest.units;
  if (audience) {
    units = units.filter((u) => u.audience.includes(audience));
  }
  // Sort by scope priority descending, then alphabetical by id
  return [...units].sort((a, b) => {
    const priDiff = scopePriority(b.scope) - scopePriority(a.scope);
    if (priDiff !== 0) return priDiff;
    return a.id.localeCompare(b.id);
  });
}

/**
 * Build the header comment block used across formats.
 */
function headerComment(manifest: KnowledgeManifest): string {
  return (
    `<!-- Generated by kcp-mcp from knowledge.yaml | project: ${manifest.project}` +
    (manifest.updated ? ` | updated: ${manifest.updated}` : "") +
    ` -->`
  );
}

/**
 * Format relationships as a markdown list.
 */
function formatRelationships(manifest: KnowledgeManifest): string[] {
  if (manifest.relationships.length === 0) return [];
  const lines: string[] = ["## Relationships", ""];
  for (const rel of manifest.relationships) {
    lines.push(`- ${rel.from_id} \u2192 ${rel.to_id} (${rel.type})`);
  }
  lines.push("");
  return lines;
}

/**
 * Format a parsed manifest into copilot-instructions.md content.
 * Exported for testing without file I/O.
 */
export function formatInstructions(
  manifest: KnowledgeManifest,
  options: GenerateInstructionsOptions = {}
): string {
  const { audience, format = "full" } = options;
  const units = prepareUnits(manifest, audience);

  if (format === "compact") {
    return formatCompact(manifest, units);
  }
  if (format === "agent") {
    return formatAgentInstructions(manifest, units);
  }
  return formatFull(manifest, units);
}

/**
 * Full verbose format (original) — ### heading blocks per unit.
 */
function formatFull(
  manifest: KnowledgeManifest,
  units: KnowledgeUnit[]
): string {
  const lines: string[] = [];

  // Header comment
  lines.push(
    `<!-- Generated by kcp-mcp --generate-instructions from knowledge.yaml -->`
  );
  lines.push(
    `<!-- Project: ${manifest.project} | Version: ${manifest.version}` +
      (manifest.kcp_version ? ` | KCP: ${manifest.kcp_version}` : "") +
      (manifest.updated ? ` | Updated: ${manifest.updated}` : "") +
      ` -->`
  );
  lines.push("");

  // Title
  lines.push(`# AI Assistant Instructions: ${manifest.project}`);
  lines.push("");
  lines.push(
    "This repository uses the Knowledge Context Protocol (KCP) to structure knowledge for AI assistants."
  );
  lines.push("");

  // Units section
  lines.push("## Available Knowledge Units");
  lines.push("");

  for (const unit of units) {
    lines.push(`### ${unit.id}`);
    lines.push(`**Intent:** ${unit.intent}`);
    lines.push(
      `**Path:** \`${unit.path}\` | **Scope:** ${unit.scope} | **Audience:** ${unit.audience.join(", ")}`
    );
    if (unit.triggers.length > 0) {
      lines.push(`*Triggers: ${unit.triggers.join(", ")}*`);
    }
    if (unit.depends_on.length > 0) {
      lines.push(`*Requires: ${unit.depends_on.join(", ")}*`);
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Relationships section
  if (manifest.relationships.length > 0) {
    lines.push("## Relationships");
    lines.push("");
    for (const rel of manifest.relationships) {
      lines.push(`- **${rel.from_id}** ${rel.type} **${rel.to_id}**`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Compact format — markdown table with one row per unit.
 */
function formatCompact(
  manifest: KnowledgeManifest,
  units: KnowledgeUnit[]
): string {
  const lines: string[] = [];

  lines.push(headerComment(manifest));
  lines.push("");
  lines.push(`# Project Knowledge Map`);
  lines.push("");
  lines.push("| ID | Intent | Path | Triggers |");
  lines.push("|----|--------|------|----------|");

  for (const unit of units) {
    const triggers = unit.triggers.length > 0 ? unit.triggers.join(", ") : "";
    lines.push(
      `| ${unit.id} | ${unit.intent} | ${unit.path} | ${triggers} |`
    );
  }

  lines.push("");
  lines.push(...formatRelationships(manifest));

  return lines.join("\n");
}

/**
 * Agent format — compact table with navigation instructions for AI agents.
 */
function formatAgentInstructions(
  manifest: KnowledgeManifest,
  units: KnowledgeUnit[]
): string {
  const lines: string[] = [];

  lines.push(headerComment(manifest));
  lines.push("");
  lines.push(`# ${manifest.project} — Knowledge Navigator`);
  lines.push("");
  lines.push(
    "You are a project knowledge navigator. Use the units below to answer questions."
  );
  lines.push(
    "When asked about a topic, find matching units by triggers/intent, then read the file."
  );
  lines.push("");
  lines.push("## Knowledge Units");
  lines.push("");
  lines.push("| ID | Intent | Path | Triggers |");
  lines.push("|----|--------|------|----------|");

  for (const unit of units) {
    const triggers = unit.triggers.length > 0 ? unit.triggers.join(", ") : "";
    lines.push(
      `| ${unit.id} | ${unit.intent} | ${unit.path} | ${triggers} |`
    );
  }

  lines.push("");
  lines.push(...formatRelationships(manifest));

  lines.push("## Instructions");
  lines.push("");
  lines.push(
    "1. Scan the table for units matching the user's question (check triggers and intent)"
  );
  lines.push("2. Use the read tool to fetch the file at the unit's path");
  lines.push("3. Summarize and mention related units");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate a .agent.md file from a knowledge.yaml manifest.
 *
 * Produces GitHub Copilot agent format with YAML frontmatter, knowledge unit
 * table, relationships, and navigation instructions.
 *
 * If maxChars is set, truncates by dropping module-scope units first,
 * then project-scope units, keeping global units and the instructions block.
 */
export function generateAgentFile(
  manifestPath: string,
  options: GenerateAgentFileOptions = {}
): string {
  const resolvedPath = resolve(manifestPath);
  const manifest = parseFile(resolvedPath);
  return formatAgentFile(manifest, options);
}

/**
 * Format a parsed manifest into .agent.md content.
 * Exported for testing without file I/O.
 */
export function formatAgentFile(
  manifest: KnowledgeManifest,
  options: GenerateAgentFileOptions = {}
): string {
  const { audience, maxChars } = options;
  let units = prepareUnits(manifest, audience);

  // If maxChars is set, drop units by ascending scope priority to fit
  if (maxChars && maxChars > 0) {
    // Try with all units; if too long, drop module-scope first, then project-scope
    const scopeOrder: string[] = ["module", "project", "global"];
    let content = buildAgentContent(manifest, units);
    for (const dropScope of scopeOrder) {
      if (content.length <= maxChars) break;
      units = units.filter((u) => u.scope !== dropScope);
      content = buildAgentContent(manifest, units);
    }
    return content.length > maxChars ? content.slice(0, maxChars) : content;
  }

  return buildAgentContent(manifest, units);
}

/**
 * Build the actual .agent.md content string.
 */
function buildAgentContent(
  manifest: KnowledgeManifest,
  units: KnowledgeUnit[]
): string {
  const lines: string[] = [];

  // YAML frontmatter
  lines.push("---");
  lines.push("name: kcp-expert");
  lines.push(
    `description: "Navigate this project's documented knowledge \u2014 ask me about any topic"`
  );
  lines.push('tools: ["read", "search"]');
  lines.push("---");
  lines.push("");
  lines.push(
    "You are a project knowledge navigator. Use the units below to answer questions."
  );
  lines.push(
    "When asked about a topic, find matching units by triggers/intent, then read the file."
  );
  lines.push("");
  lines.push("## Knowledge Units");
  lines.push("");
  lines.push("| ID | Intent | Path | Triggers |");
  lines.push("|----|--------|------|----------|");

  for (const unit of units) {
    const triggers = unit.triggers.length > 0 ? unit.triggers.join(", ") : "";
    lines.push(
      `| ${unit.id} | ${unit.intent} | ${unit.path} | ${triggers} |`
    );
  }

  lines.push("");

  // Relationships
  if (manifest.relationships.length > 0) {
    lines.push("## Relationships");
    lines.push("");
    for (const rel of manifest.relationships) {
      lines.push(`- ${rel.from_id} \u2192 ${rel.to_id} (${rel.type})`);
    }
    lines.push("");
  }

  lines.push("## Instructions");
  lines.push("");
  lines.push(
    "1. Scan the table for units matching the user's question (check triggers and intent)"
  );
  lines.push("2. Use the read tool to fetch the file at the unit's path");
  lines.push("3. Summarize and mention related units");
  lines.push("");

  return lines.join("\n");
}
