// Generate path-specific .instructions.md files from a knowledge.yaml manifest.
// Each file gets YAML frontmatter with `applyTo` patterns for Copilot path matching.

import { resolve, dirname, join } from "node:path";
import { writeFileSync, mkdirSync } from "node:fs";
import { parseFile } from "./parser.js";
import { scopePriority } from "./mapper.js";
import type { KnowledgeManifest, KnowledgeUnit } from "./model.js";

export interface SplitInstructionsOptions {
  splitBy: "directory" | "scope" | "unit" | "none";
  audience?: string;
}

/**
 * Generate split instruction files from a knowledge.yaml manifest.
 *
 * Groups units by the chosen strategy, writes one `{group}.instructions.md`
 * per group into `outputDir`, each with YAML frontmatter containing `applyTo`
 * patterns that Copilot uses for path-specific instruction injection.
 */
export function generateSplitInstructions(
  manifestPath: string,
  outputDir: string,
  options: SplitInstructionsOptions
): void {
  const resolvedPath = resolve(manifestPath);
  const manifest = parseFile(resolvedPath);
  const resolvedOutputDir = resolve(outputDir);

  mkdirSync(resolvedOutputDir, { recursive: true });

  const { splitBy, audience } = options;

  // Filter units by audience if specified
  let units: KnowledgeUnit[] = manifest.units;
  if (audience) {
    units = units.filter((u) => u.audience.includes(audience));
  }

  // Sort units
  units = [...units].sort((a, b) => {
    const priDiff = scopePriority(b.scope) - scopePriority(a.scope);
    if (priDiff !== 0) return priDiff;
    return a.id.localeCompare(b.id);
  });

  if (splitBy === "none") {
    // Single file with all units
    const content = buildInstructionFile(manifest, units, "**");
    writeFileSync(join(resolvedOutputDir, "all.instructions.md"), content);
    return;
  }

  // Group units
  const groups = groupUnits(units, splitBy);

  for (const [groupName, groupUnits] of groups.entries()) {
    const applyTo = buildApplyTo(groupUnits, splitBy);
    const safeName = groupName.replace(/[^a-z0-9_-]/gi, "-").replace(/^-|-$/g, "");
    const fileName = `${safeName || "root"}.instructions.md`;
    const content = buildInstructionFile(manifest, groupUnits, applyTo);
    writeFileSync(join(resolvedOutputDir, fileName), content);
  }
}

/**
 * Group units by the chosen strategy.
 */
function groupUnits(
  units: KnowledgeUnit[],
  splitBy: "directory" | "scope" | "unit"
): Map<string, KnowledgeUnit[]> {
  const groups = new Map<string, KnowledgeUnit[]>();

  for (const unit of units) {
    let key: string;

    switch (splitBy) {
      case "directory": {
        const dir = dirname(unit.path);
        key = dir === "." ? "root" : dir.split("/")[0]!;
        break;
      }
      case "scope":
        key = unit.scope;
        break;
      case "unit":
        key = unit.id;
        break;
    }

    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(unit);
  }

  return groups;
}

/**
 * Build the `applyTo` glob patterns for a group of units.
 * Combines directory-based and trigger-based patterns (max 5 total).
 */
function buildApplyTo(
  units: KnowledgeUnit[],
  splitBy: "directory" | "scope" | "unit"
): string {
  const patterns = new Set<string>();

  if (splitBy === "scope") {
    // For scope-based splitting, use broad patterns
    const scopes = new Set(units.map((u) => u.scope));
    if (scopes.has("global")) {
      patterns.add("**");
    } else if (scopes.has("project")) {
      patterns.add("src/**");
    } else {
      // module scope: use directory-based patterns
      for (const unit of units) {
        const dir = dirname(unit.path);
        patterns.add(dir === "." ? "**" : `${dir}/**`);
      }
    }
  } else {
    // directory or unit: use path-based patterns
    for (const unit of units) {
      const dir = dirname(unit.path);
      if (dir !== ".") {
        patterns.add(`${dir}/**`);
      }
    }

    // Add trigger-based globs (up to 5 total patterns)
    for (const unit of units) {
      for (const trigger of unit.triggers) {
        if (patterns.size >= 5) break;
        patterns.add(`**/*${trigger}*`);
      }
      if (patterns.size >= 5) break;
    }
  }

  // Ensure at least one pattern
  if (patterns.size === 0) {
    patterns.add("**");
  }

  return [...patterns].join(",");
}

/**
 * Build a single .instructions.md file content with YAML frontmatter.
 */
function buildInstructionFile(
  manifest: KnowledgeManifest,
  units: KnowledgeUnit[],
  applyTo: string
): string {
  const lines: string[] = [];

  // YAML frontmatter
  lines.push("---");
  lines.push(`applyTo: "${applyTo}"`);
  lines.push("---");
  lines.push("");

  // Header comment
  lines.push(
    `<!-- Generated by kcp-mcp from knowledge.yaml | project: ${manifest.project}` +
      (manifest.updated ? ` | updated: ${manifest.updated}` : "") +
      ` -->`
  );
  lines.push("");

  // Title
  lines.push(`# ${manifest.project} — Knowledge Units`);
  lines.push("");

  // Compact table
  lines.push("| ID | Intent | Path | Triggers |");
  lines.push("|----|--------|------|----------|");

  for (const unit of units) {
    const triggers = unit.triggers.length > 0 ? unit.triggers.join(", ") : "";
    lines.push(
      `| ${unit.id} | ${unit.intent} | ${unit.path} | ${triggers} |`
    );
  }

  lines.push("");

  // Relationships (only those involving units in this group)
  const unitIds = new Set(units.map((u) => u.id));
  const relevantRels = manifest.relationships.filter(
    (r) => unitIds.has(r.from_id) || unitIds.has(r.to_id)
  );

  if (relevantRels.length > 0) {
    lines.push("## Relationships");
    lines.push("");
    for (const rel of relevantRels) {
      lines.push(`- ${rel.from_id} \u2192 ${rel.to_id} (${rel.type})`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
