package no.cantara.kcp.mcp;

import no.cantara.kcp.KcpParser;
import no.cantara.kcp.model.KnowledgeManifest;
import org.junit.jupiter.api.Test;

import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for KcpInstructions format support (COMPACT, AGENT) and generateAgentFile().
 */
class KcpInstructionsFormatTest {

    private static Path fixture(String name) {
        URL url = KcpInstructionsFormatTest.class.getClassLoader()
            .getResource("fixtures/" + name + "/knowledge.yaml");
        assertNotNull(url, "fixture not found: " + name);
        return Paths.get(url.getPath());
    }

    // ── COMPACT format ────────────────────────────────────────────────────────

    @Test void compactFormatHasMarkdownTable() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.COMPACT);

        assertTrue(output.contains("| ID | Intent | Path | Triggers |"));
        assertTrue(output.contains("|----|--------|------|----------|"));
    }

    @Test void compactFormatHasProjectKnowledgeMapTitle() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.COMPACT);

        assertTrue(output.contains("# Project Knowledge Map"));
    }

    @Test void compactFormatContainsHeaderComment() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.COMPACT);

        assertTrue(output.contains("<!-- Generated by kcp-mcp from knowledge.yaml | project: full-example"));
    }

    @Test void compactFormatContainsAllUnitRows() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.COMPACT);

        assertTrue(output.contains("| spec |"));
        assertTrue(output.contains("| api-schema |"));
        assertTrue(output.contains("| guide |"));
    }

    @Test void compactFormatContainsRelationships() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.COMPACT);

        assertTrue(output.contains("## Relationships"));
        assertTrue(output.contains("api-schema \u2192 spec (context)"));
    }

    @Test void compactFormatDoesNotHaveHeadingBlocks() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.COMPACT);

        // Compact should NOT have the ### heading blocks that FULL format uses
        assertFalse(output.contains("### spec"));
        assertFalse(output.contains("### api-schema"));
    }

    // ── AGENT format ──────────────────────────────────────────────────────────

    @Test void agentFormatHasKnowledgeNavigatorTitle() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.AGENT);

        assertTrue(output.contains("# full-example \u2014 Knowledge Navigator"));
    }

    @Test void agentFormatHasNavigationInstructions() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.AGENT);

        assertTrue(output.contains("## Instructions"));
        assertTrue(output.contains("1. Scan the table for units matching the user's question"));
        assertTrue(output.contains("2. Use the read tool to fetch the file at the unit's path"));
        assertTrue(output.contains("3. Summarize and mention related units"));
    }

    @Test void agentFormatHasCompactTable() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.AGENT);

        assertTrue(output.contains("| ID | Intent | Path | Triggers |"));
        assertTrue(output.contains("| spec |"));
    }

    // ── generateAgentFile ─────────────────────────────────────────────────────

    @Test void generateAgentFileHasYamlFrontmatter() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatAgentFile(manifest, null, 0);

        assertTrue(output.startsWith("---\n"));
        assertTrue(output.contains("name: kcp-expert"));
        assertTrue(output.contains("description: \"Navigate this project's documented knowledge"));
        assertTrue(output.contains("tools: [\"read\", \"search\"]"));
        // Check that frontmatter is closed
        int firstDashes = output.indexOf("---");
        int secondDashes = output.indexOf("---", firstDashes + 3);
        assertTrue(secondDashes > firstDashes, "YAML frontmatter should have opening and closing ---");
    }

    @Test void generateAgentFileContainsAllUnits() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatAgentFile(manifest, null, 0);

        assertTrue(output.contains("| spec |"));
        assertTrue(output.contains("| api-schema |"));
        assertTrue(output.contains("| guide |"));
    }

    @Test void generateAgentFileContainsInstructions() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatAgentFile(manifest, null, 0);

        assertTrue(output.contains("## Instructions"));
        assertTrue(output.contains("1. Scan the table"));
    }

    @Test void generateAgentFileRespectsMaxCharsDropsModuleFirst() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));

        // Get full content length first
        String full = KcpInstructions.formatAgentFile(manifest, null, 0);

        // Set maxChars to something smaller but big enough to hold content without module units
        // module scope unit is api-schema
        String withoutModule = KcpInstructions.formatAgentFile(manifest, null, full.length() - 10);

        // Module-scope unit (api-schema) should be dropped first
        assertFalse(withoutModule.contains("| api-schema |"),
            "module-scope unit should be dropped when maxChars forces truncation");
        // Global (spec) should still be present
        assertTrue(withoutModule.contains("| spec |"),
            "global-scope unit should be retained");
    }

    @Test void generateAgentFileWithVerySmallMaxCharsTruncates() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatAgentFile(manifest, null, 100);

        assertEquals(100, output.length(),
            "Output should be truncated to exactly maxChars when content exceeds limit");
    }

    @Test void generateAgentFileWithAudienceFilter() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatAgentFile(manifest, "agent", 0);

        assertTrue(output.contains("| spec |"));
        assertTrue(output.contains("| api-schema |"));
        assertFalse(output.contains("| guide |"), "guide has no agent audience and should be filtered");
    }

    // ── FULL format backward compatibility ────────────────────────────────────

    @Test void fullFormatMatchesOriginalOutput() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String original = KcpInstructions.formatInstructions(manifest, null);
        String explicit = KcpInstructions.formatInstructions(manifest, null, KcpInstructions.Format.FULL);

        assertEquals(original, explicit, "2-arg overload should produce same output as FULL format");
    }

    // ── generateInstructions file I/O with format ─────────────────────────────

    @Test void generateInstructionsFileCompactFormat() throws Exception {
        String output = KcpInstructions.generateInstructions(
            fixture("full"), null, KcpInstructions.Format.COMPACT);

        assertTrue(output.contains("# Project Knowledge Map"));
        assertTrue(output.contains("| ID | Intent | Path | Triggers |"));
    }

    @Test void generateInstructionsFileAgentFormat() throws Exception {
        String output = KcpInstructions.generateInstructions(
            fixture("full"), null, KcpInstructions.Format.AGENT);

        assertTrue(output.contains("Knowledge Navigator"));
        assertTrue(output.contains("## Instructions"));
    }
}
