package no.cantara.kcp.mcp;

import no.cantara.kcp.KcpParser;
import no.cantara.kcp.model.KnowledgeManifest;
import org.junit.jupiter.api.Test;

import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class KcpInstructionsTest {

    private static Path fixture(String name) {
        URL url = KcpInstructionsTest.class.getClassLoader()
            .getResource("fixtures/" + name + "/knowledge.yaml");
        assertNotNull(url, "fixture not found: " + name);
        return Paths.get(url.getPath());
    }

    // ── formatInstructions ────────────────────────────────────────────────────

    @Test void formatInstructionsIncludesAllUnitsWhenNoAudienceFilter() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        // All 3 units should be present
        assertTrue(output.contains("### spec"));
        assertTrue(output.contains("### api-schema"));
        assertTrue(output.contains("### guide"));
    }

    @Test void formatInstructionsFiltersByAudience() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        // "agent" audience: spec (human+agent+developer) and api-schema (developer+agent) match
        // guide (human+developer) does NOT match
        String output = KcpInstructions.formatInstructions(manifest, "agent");

        assertTrue(output.contains("### spec"));
        assertTrue(output.contains("### api-schema"));
        assertFalse(output.contains("### guide"));
    }

    @Test void formatInstructionsSortsGlobalScopeFirst() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        // global (spec) should appear before module (api-schema) and project (guide)
        int specIdx = output.indexOf("### spec");
        int apiIdx  = output.indexOf("### api-schema");
        int guideIdx = output.indexOf("### guide");

        assertTrue(specIdx < apiIdx, "global scope 'spec' should appear before module scope 'api-schema'");
        assertTrue(specIdx < guideIdx, "global scope 'spec' should appear before project scope 'guide'");
    }

    @Test void formatInstructionsIncludesRelationships() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        assertTrue(output.contains("## Relationships"));
        assertTrue(output.contains("**api-schema** context **spec**"));
        assertTrue(output.contains("**guide** context **spec**"));
    }

    @Test void formatInstructionsContainsHeaderComment() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        assertTrue(output.contains("<!-- Generated by kcp-mcp --generate-instructions from knowledge.yaml -->"));
        assertTrue(output.contains("<!-- Project: full-example"));
        assertTrue(output.contains("Version: 2.1.0"));
        assertTrue(output.contains("KCP: 0.6"));
    }

    @Test void formatInstructionsContainsTitle() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        assertTrue(output.contains("# AI Assistant Instructions: full-example"));
        assertTrue(output.contains("Knowledge Context Protocol"));
    }

    @Test void formatInstructionsIncludesTriggers() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        assertTrue(output.contains("*Triggers: spec, rules, normative*"));
    }

    @Test void formatInstructionsIncludesDependsOn() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        assertTrue(output.contains("*Requires: spec*"));
    }

    @Test void formatInstructionsIncludesUnitMetadata() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("full"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        assertTrue(output.contains("**Intent:**"));
        assertTrue(output.contains("**Path:**"));
        assertTrue(output.contains("**Scope:**"));
        assertTrue(output.contains("**Audience:**"));
    }

    // ── generateInstructions (file I/O) ───────────────────────────────────────

    @Test void generateInstructionsReadsFromFixtureFile() throws Exception {
        String output = KcpInstructions.generateInstructions(fixture("full"), null);
        assertNotNull(output);
        assertTrue(output.contains("full-example"));
        assertTrue(output.contains("### spec"));
    }

    @Test void generateInstructionsWithAudienceFilter() throws Exception {
        String output = KcpInstructions.generateInstructions(fixture("full"), "agent");
        assertTrue(output.contains("### spec"));
        assertTrue(output.contains("### api-schema"));
        assertFalse(output.contains("### guide"));
    }

    // ── Minimal fixture (no triggers, no relationships) ───────────────────────

    @Test void formatInstructionsMinimalFixture() throws Exception {
        KnowledgeManifest manifest = KcpParser.parse(fixture("minimal"));
        String output = KcpInstructions.formatInstructions(manifest, null);

        assertTrue(output.contains("# AI Assistant Instructions: my-project"));
        assertTrue(output.contains("### overview"));
        // No relationships section for minimal fixture
        assertFalse(output.contains("## Relationships"));
    }
}
