import { describe, it, expect } from "vitest";
import { join } from "node:path";
import { generateInstructions, formatInstructions } from "../src/instructions.js";
import { parseFile } from "../src/parser.js";

const FULL_DIR = join(import.meta.dirname, "fixtures/full");
const MINIMAL_DIR = join(import.meta.dirname, "fixtures/minimal");

describe("generateInstructions", () => {
  it("generates markdown from the minimal fixture", () => {
    const md = generateInstructions(join(MINIMAL_DIR, "knowledge.yaml"));

    expect(md).toContain("# AI Assistant Instructions: my-project");
    expect(md).toContain("## Available Knowledge Units");
    expect(md).toContain("### overview");
    expect(md).toContain("**Intent:** What is this project and how do I get started?");
    expect(md).toContain("**Path:** `README.md`");
  });

  it("includes header comment with project metadata", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("<!-- Generated by kcp-mcp --generate-instructions");
    expect(md).toContain("Project: full-example");
    expect(md).toContain("Version: 2.1.0");
    expect(md).toContain("KCP: 0.5");
    expect(md).toContain("Updated: 2026-02-28");
  });

  it("includes all units from full fixture", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("### spec");
    expect(md).toContain("### api-schema");
    expect(md).toContain("### guide");
  });

  it("includes triggers when present", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("*Triggers: spec, rules, normative*");
  });

  it("includes depends_on as Requires", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("*Requires: spec*");
  });

  it("includes relationships section", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("## Relationships");
    expect(md).toContain("**api-schema** context **spec**");
    expect(md).toContain("**guide** context **spec**");
  });

  it("omits relationships section when none exist", () => {
    const md = generateInstructions(join(MINIMAL_DIR, "knowledge.yaml"));

    expect(md).not.toContain("## Relationships");
  });
});

describe("generateInstructions with audience filter", () => {
  it("filters units by audience when specified", () => {
    // In full fixture: spec (human, agent, developer), api-schema (developer, agent), guide (human, developer)
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      audience: "agent",
    });

    expect(md).toContain("### spec");
    expect(md).toContain("### api-schema");
    expect(md).not.toContain("### guide"); // guide has no "agent" audience
  });

  it("includes all units when no audience filter", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("### spec");
    expect(md).toContain("### api-schema");
    expect(md).toContain("### guide");
  });
});

describe("formatInstructions sorting", () => {
  it("sorts global-scope units before project-scope and module-scope", () => {
    const manifest = parseFile(join(FULL_DIR, "knowledge.yaml"));
    const md = formatInstructions(manifest);

    // spec is global (priority 1.0), guide is project (0.7), api-schema is module (0.5)
    const specIdx = md.indexOf("### spec");
    const guideIdx = md.indexOf("### guide");
    const apiIdx = md.indexOf("### api-schema");

    expect(specIdx).toBeLessThan(guideIdx);
    expect(guideIdx).toBeLessThan(apiIdx);
  });
});
