import { describe, it, expect } from "vitest";
import { join } from "node:path";
import {
  generateInstructions,
  formatInstructions,
  generateAgentFile,
  formatAgentFile,
} from "../src/instructions.js";
import { parseFile } from "../src/parser.js";

const FULL_DIR = join(import.meta.dirname, "fixtures/full");
const MINIMAL_DIR = join(import.meta.dirname, "fixtures/minimal");

describe("generateInstructions", () => {
  it("generates markdown from the minimal fixture", () => {
    const md = generateInstructions(join(MINIMAL_DIR, "knowledge.yaml"));

    expect(md).toContain("# AI Assistant Instructions: my-project");
    expect(md).toContain("## Available Knowledge Units");
    expect(md).toContain("### overview");
    expect(md).toContain("**Intent:** What is this project and how do I get started?");
    expect(md).toContain("**Path:** `README.md`");
  });

  it("includes header comment with project metadata", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("<!-- Generated by kcp-mcp --generate-instructions");
    expect(md).toContain("Project: full-example");
    expect(md).toContain("Version: 2.1.0");
    expect(md).toContain("KCP: 0.5");
    expect(md).toContain("Updated: 2026-02-28");
  });

  it("includes all units from full fixture", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("### spec");
    expect(md).toContain("### api-schema");
    expect(md).toContain("### guide");
  });

  it("includes triggers when present", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("*Triggers: spec, rules, normative*");
  });

  it("includes depends_on as Requires", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("*Requires: spec*");
  });

  it("includes relationships section", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("## Relationships");
    expect(md).toContain("**api-schema** context **spec**");
    expect(md).toContain("**guide** context **spec**");
  });

  it("omits relationships section when none exist", () => {
    const md = generateInstructions(join(MINIMAL_DIR, "knowledge.yaml"));

    expect(md).not.toContain("## Relationships");
  });
});

describe("generateInstructions with audience filter", () => {
  it("filters units by audience when specified", () => {
    // In full fixture: spec (human, agent, developer), api-schema (developer, agent), guide (human, developer)
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      audience: "agent",
    });

    expect(md).toContain("### spec");
    expect(md).toContain("### api-schema");
    expect(md).not.toContain("### guide"); // guide has no "agent" audience
  });

  it("includes all units when no audience filter", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("### spec");
    expect(md).toContain("### api-schema");
    expect(md).toContain("### guide");
  });
});

describe("formatInstructions sorting", () => {
  it("sorts global-scope units before project-scope and module-scope", () => {
    const manifest = parseFile(join(FULL_DIR, "knowledge.yaml"));
    const md = formatInstructions(manifest);

    // spec is global (priority 1.0), guide is project (0.7), api-schema is module (0.5)
    const specIdx = md.indexOf("### spec");
    const guideIdx = md.indexOf("### guide");
    const apiIdx = md.indexOf("### api-schema");

    expect(specIdx).toBeLessThan(guideIdx);
    expect(guideIdx).toBeLessThan(apiIdx);
  });
});

describe("compact format", () => {
  it("generates a markdown table with header row", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "compact",
    });

    expect(md).toContain("| ID | Intent | Path | Triggers |");
    expect(md).toContain("|----|--------|------|----------|");
  });

  it("includes all units as table rows", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "compact",
    });

    expect(md).toContain("| spec |");
    expect(md).toContain("| api-schema |");
    expect(md).toContain("| guide |");
  });

  it("includes project header comment", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "compact",
    });

    expect(md).toContain("<!-- Generated by kcp-mcp from knowledge.yaml");
    expect(md).toContain("project: full-example");
  });

  it("includes Project Knowledge Map title", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "compact",
    });

    expect(md).toContain("# Project Knowledge Map");
  });

  it("includes relationships with arrow notation", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "compact",
    });

    expect(md).toContain("api-schema \u2192 spec (context)");
    expect(md).toContain("guide \u2192 spec (context)");
  });

  it("respects audience filter in compact format", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "compact",
      audience: "agent",
    });

    expect(md).toContain("| spec |");
    expect(md).toContain("| api-schema |");
    expect(md).not.toContain("| guide |");
  });
});

describe("agent format (via format option)", () => {
  it("includes navigator instructions", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "agent",
    });

    expect(md).toContain("You are a project knowledge navigator");
    expect(md).toContain("## Instructions");
    expect(md).toContain("Scan the table for units");
  });

  it("includes a table", () => {
    const md = generateInstructions(join(FULL_DIR, "knowledge.yaml"), {
      format: "agent",
    });

    expect(md).toContain("| ID | Intent | Path | Triggers |");
    expect(md).toContain("| spec |");
  });
});

describe("generateAgentFile", () => {
  it("starts with YAML frontmatter", () => {
    const md = generateAgentFile(join(FULL_DIR, "knowledge.yaml"));

    expect(md.startsWith("---\n")).toBe(true);
    expect(md).toContain("name: kcp-expert");
    expect(md).toContain('tools: ["read", "search"]');
  });

  it("contains a knowledge units table", () => {
    const md = generateAgentFile(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("## Knowledge Units");
    expect(md).toContain("| ID | Intent | Path | Triggers |");
    expect(md).toContain("| spec |");
    expect(md).toContain("| api-schema |");
    expect(md).toContain("| guide |");
  });

  it("contains relationships", () => {
    const md = generateAgentFile(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("## Relationships");
    expect(md).toContain("api-schema \u2192 spec (context)");
  });

  it("contains instructions block", () => {
    const md = generateAgentFile(join(FULL_DIR, "knowledge.yaml"));

    expect(md).toContain("## Instructions");
    expect(md).toContain("Scan the table for units");
    expect(md).toContain("Use the read tool");
    expect(md).toContain("Summarize and mention related units");
  });

  it("respects audience filter", () => {
    const md = generateAgentFile(join(FULL_DIR, "knowledge.yaml"), {
      audience: "agent",
    });

    expect(md).toContain("| spec |");
    expect(md).toContain("| api-schema |");
    expect(md).not.toContain("| guide |");
  });

  it("respects maxChars by dropping lower-scope units", () => {
    const fullMd = generateAgentFile(join(FULL_DIR, "knowledge.yaml"));
    const shortMd = generateAgentFile(join(FULL_DIR, "knowledge.yaml"), {
      maxChars: fullMd.length - 50,
    });

    // Should have dropped module-scope units first (api-schema)
    expect(shortMd.length).toBeLessThanOrEqual(fullMd.length - 50);
  });
});

describe("formatAgentFile (no file I/O)", () => {
  it("produces valid agent file from parsed manifest", () => {
    const manifest = parseFile(join(MINIMAL_DIR, "knowledge.yaml"));
    const md = formatAgentFile(manifest);

    expect(md.startsWith("---\n")).toBe(true);
    expect(md).toContain("name: kcp-expert");
    expect(md).toContain("| overview |");
  });
});
