package no.cantara.kcp.mcp;

import no.cantara.kcp.KcpParser;
import no.cantara.kcp.model.KnowledgeManifest;
import no.cantara.kcp.model.KnowledgeUnit;
import no.cantara.kcp.model.Relationship;

import java.io.IOException;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates copilot-instructions.md content from a knowledge.yaml manifest.
 * Java equivalent of the TypeScript instructions.ts.
 */
public final class KcpInstructions {

    private KcpInstructions() {}

    private static final Map<String, Double> SCOPE_PRIORITY = Map.of(
        "global",  1.0,
        "project", 0.7,
        "module",  0.5
    );

    /**
     * Generate copilot-instructions.md content from a knowledge.yaml file.
     *
     * @param manifestPath path to the knowledge.yaml file
     * @param audience     optional audience filter (null = include all)
     * @return formatted markdown content
     * @throws IOException if the manifest cannot be read
     */
    public static String generateInstructions(Path manifestPath, String audience) throws IOException {
        KnowledgeManifest manifest = KcpParser.parse(manifestPath);
        return formatInstructions(manifest, audience);
    }

    /**
     * Format a parsed manifest into copilot-instructions.md content.
     * Package-private for direct testing without file I/O.
     *
     * <p>Units are sorted by scope priority (global first) then alphabetically by id.
     * If an audience filter is provided, only units matching that audience are included.</p>
     *
     * @param manifest the parsed knowledge manifest
     * @param audience optional audience filter (null = include all)
     * @return formatted markdown content
     */
    static String formatInstructions(KnowledgeManifest manifest, String audience) {
        // Filter units by audience if specified
        List<KnowledgeUnit> units = manifest.units();
        if (audience != null && !audience.isEmpty()) {
            units = units.stream()
                .filter(u -> u.audience() != null && u.audience().contains(audience))
                .collect(Collectors.toList());
        }

        // Sort by scope priority descending, then alphabetical by id
        units = new ArrayList<>(units);
        units.sort((a, b) -> {
            double priA = SCOPE_PRIORITY.getOrDefault(a.scope() != null ? a.scope() : "global", 0.5);
            double priB = SCOPE_PRIORITY.getOrDefault(b.scope() != null ? b.scope() : "global", 0.5);
            int priDiff = Double.compare(priB, priA);
            if (priDiff != 0) return priDiff;
            return a.id().compareTo(b.id());
        });

        List<String> lines = new ArrayList<>();

        // Header comment
        lines.add("<!-- Generated by kcp-mcp --generate-instructions from knowledge.yaml -->");

        StringBuilder meta = new StringBuilder();
        meta.append("<!-- Project: ").append(manifest.project());
        meta.append(" | Version: ").append(manifest.version());
        if (manifest.kcpVersion() != null && !manifest.kcpVersion().isEmpty()) {
            meta.append(" | KCP: ").append(manifest.kcpVersion());
        }
        if (manifest.updated() != null) {
            meta.append(" | Updated: ").append(manifest.updated());
        }
        meta.append(" -->");
        lines.add(meta.toString());
        lines.add("");

        // Title
        lines.add("# AI Assistant Instructions: " + manifest.project());
        lines.add("");
        lines.add("This repository uses the Knowledge Context Protocol (KCP) to structure knowledge for AI assistants.");
        lines.add("");

        // Units section
        lines.add("## Available Knowledge Units");
        lines.add("");

        for (KnowledgeUnit unit : units) {
            lines.add("### " + unit.id());
            lines.add("**Intent:** " + unit.intent());

            String audienceStr = unit.audience() != null
                ? String.join(", ", unit.audience())
                : "";
            lines.add("**Path:** `" + unit.path() + "` | **Scope:** " + unit.scope()
                + " | **Audience:** " + audienceStr);

            if (unit.triggers() != null && !unit.triggers().isEmpty()) {
                lines.add("*Triggers: " + String.join(", ", unit.triggers()) + "*");
            }
            if (unit.dependsOn() != null && !unit.dependsOn().isEmpty()) {
                lines.add("*Requires: " + String.join(", ", unit.dependsOn()) + "*");
            }
            lines.add("");
            lines.add("---");
            lines.add("");
        }

        // Relationships section
        List<Relationship> relationships = manifest.relationships();
        if (relationships != null && !relationships.isEmpty()) {
            lines.add("## Relationships");
            lines.add("");
            for (Relationship rel : relationships) {
                lines.add("- **" + rel.fromId() + "** " + rel.type() + " **" + rel.toId() + "**");
            }
            lines.add("");
        }

        return String.join("\n", lines);
    }
}
